name: Setup

runs:
  using: composite
  steps:
    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: 18.15
    - name: Cache
      uses: actions/cache@v4
      id: cache
      with:
        path: '**/node_modules'
        key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
    - name: Install
      run: yarn --immutable
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
