/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import {BytesLike} from "@ethersproject/bytes";
import {Listener, Provider} from "@ethersproject/providers";
import {FunctionFragment, EventFragment, Result} from "@ethersproject/abi";
import {TypedEventFilter, TypedEvent, TypedListener} from "./commons";

interface SmartWalletCheckerInterface extends ethers.utils.Interface {
  functions: {
    "allowlistAddress(address)": FunctionFragment;
    "check(address)": FunctionFragment;
    "denylistAddress(address)": FunctionFragment;
    "getActionId(bytes4)": FunctionFragment;
    "getAllowlistedAddress(uint256)": FunctionFragment;
    "getAllowlistedAddressesLength()": FunctionFragment;
    "getAuthorizer()": FunctionFragment;
    "getVault()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "allowlistAddress",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "check", values: [string]): string;
  encodeFunctionData(
    functionFragment: "denylistAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getActionId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllowlistedAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllowlistedAddressesLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAuthorizer",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getVault", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "allowlistAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "check", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "denylistAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllowlistedAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllowlistedAddressesLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuthorizer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVault", data: BytesLike): Result;

  events: {
    "ContractAddressAdded(address)": EventFragment;
    "ContractAddressRemoved(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ContractAddressAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ContractAddressRemoved"): EventFragment;
}

export class SmartWalletChecker extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SmartWalletCheckerInterface;

  functions: {
    allowlistAddress(
      contractAddress: string,
      overrides?: Overrides & {from?: string | Promise<string>}
    ): Promise<ContractTransaction>;

    check(
      contractAddress: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    denylistAddress(
      contractAddress: string,
      overrides?: Overrides & {from?: string | Promise<string>}
    ): Promise<ContractTransaction>;

    getActionId(
      selector: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getAllowlistedAddress(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getAllowlistedAddressesLength(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getAuthorizer(overrides?: CallOverrides): Promise<[string]>;

    getVault(overrides?: CallOverrides): Promise<[string]>;
  };

  allowlistAddress(
    contractAddress: string,
    overrides?: Overrides & {from?: string | Promise<string>}
  ): Promise<ContractTransaction>;

  check(contractAddress: string, overrides?: CallOverrides): Promise<boolean>;

  denylistAddress(
    contractAddress: string,
    overrides?: Overrides & {from?: string | Promise<string>}
  ): Promise<ContractTransaction>;

  getActionId(selector: BytesLike, overrides?: CallOverrides): Promise<string>;

  getAllowlistedAddress(
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getAllowlistedAddressesLength(overrides?: CallOverrides): Promise<BigNumber>;

  getAuthorizer(overrides?: CallOverrides): Promise<string>;

  getVault(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    allowlistAddress(
      contractAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    check(contractAddress: string, overrides?: CallOverrides): Promise<boolean>;

    denylistAddress(
      contractAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getActionId(
      selector: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    getAllowlistedAddress(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getAllowlistedAddressesLength(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAuthorizer(overrides?: CallOverrides): Promise<string>;

    getVault(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    ContractAddressAdded(
      contractAddress?: null
    ): TypedEventFilter<[string], {contractAddress: string}>;

    ContractAddressRemoved(
      contractAddress?: null
    ): TypedEventFilter<[string], {contractAddress: string}>;
  };

  estimateGas: {
    allowlistAddress(
      contractAddress: string,
      overrides?: Overrides & {from?: string | Promise<string>}
    ): Promise<BigNumber>;

    check(
      contractAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    denylistAddress(
      contractAddress: string,
      overrides?: Overrides & {from?: string | Promise<string>}
    ): Promise<BigNumber>;

    getActionId(
      selector: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAllowlistedAddress(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAllowlistedAddressesLength(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAuthorizer(overrides?: CallOverrides): Promise<BigNumber>;

    getVault(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    allowlistAddress(
      contractAddress: string,
      overrides?: Overrides & {from?: string | Promise<string>}
    ): Promise<PopulatedTransaction>;

    check(
      contractAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    denylistAddress(
      contractAddress: string,
      overrides?: Overrides & {from?: string | Promise<string>}
    ): Promise<PopulatedTransaction>;

    getActionId(
      selector: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAllowlistedAddress(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAllowlistedAddressesLength(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAuthorizer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getVault(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
