/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {Contract, Signer, utils} from "ethers";
import {Provider} from "@ethersproject/providers";
import type {
  BALTokenHolderFactory,
  BALTokenHolderFactoryInterface,
} from "../BALTokenHolderFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IBalancerToken",
        name: "balancerToken",
        type: "address",
      },
      {
        internalType: "contract IVault",
        name: "vault",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "contract BALTokenHolder",
        name: "balTokenHolder",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "name",
        type: "string",
      },
    ],
    name: "BALTokenHolderCreated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
    ],
    name: "create",
    outputs: [
      {
        internalType: "contract IBALTokenHolder",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getBalancerToken",
    outputs: [
      {
        internalType: "contract IBalancerToken",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getVault",
    outputs: [
      {
        internalType: "contract IVault",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "holder",
        type: "address",
      },
    ],
    name: "isHolderFromFactory",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class BALTokenHolderFactory__factory {
  static readonly abi = _abi;
  static createInterface(): BALTokenHolderFactoryInterface {
    return new utils.Interface(_abi) as BALTokenHolderFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BALTokenHolderFactory {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as BALTokenHolderFactory;
  }
}
