/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {Contract, Signer, utils} from "ethers";
import {Provider} from "@ethersproject/providers";
import type {
  WstETHRateProvider,
  WstETHRateProviderInterface,
} from "../WstETHRateProvider";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IwstETH",
        name: "_wstETH",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "getRate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "wstETH",
    outputs: [
      {
        internalType: "contract IwstETH",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class WstETHRateProvider__factory {
  static readonly abi = _abi;
  static createInterface(): WstETHRateProviderInterface {
    return new utils.Interface(_abi) as WstETHRateProviderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): WstETHRateProvider {
    return new Contract(address, _abi, signerOrProvider) as WstETHRateProvider;
  }
}
